services:
    database:
        image: postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: picpay
        volumes:
            - "./PicPayChallenge.Infra/Migrations/scripts:/docker-entrypoint-initdb.d"
    api:
        image: bloiseleo/picpayapi:latest
        depends_on:
            - database 
        ports:
            - "8080:8080"
            