CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "Password" text NOT NULL,
    "Document" text NOT NULL,
    "Kind" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_Users_Document" ON "Users" ("Document");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241123015051_CreateUserTable', '9.0.0');

CREATE TABLE "Transactions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FromId" integer NOT NULL,
    "ToId" integer NOT NULL,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Transactions_Users_FromId" FOREIGN KEY ("FromId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Transactions_Users_ToId" FOREIGN KEY ("ToId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Wallets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Amount" numeric NOT NULL,
    CONSTRAINT "PK_Wallets" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Wallets_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Transactions_FromId" ON "Transactions" ("FromId");

CREATE INDEX "IX_Transactions_ToId" ON "Transactions" ("ToId");

CREATE INDEX "IX_Wallets_UserId" ON "Wallets" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241126234243_CreateWalletsAndTransactions', '9.0.0');

ALTER TABLE "Transactions" ADD "Amount" numeric NOT NULL DEFAULT 0.0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241127160533_AddAmountFieldToTransaction', '9.0.0');

COMMIT;


